### ISSUE TITLE
Is it possible to not update the hosts file?

### ISSUE THREAD

**Issue by adrienjoly** [theopenconversationkit/tock-docker#15]
In the https://github.com/theopenconversationkit/tock-docker#connect-to-the-mongo-database-from-an-ide section of the README, we are invited to update our `hosts` file in order to map `mongo`, `mongo2` and `mongo3` hostnames to 127.0.0.1.

I would rather avoid doing that, to prevent possible side effects with other projects I'm working on. (i.e. in case I forget to remove these lines from `hosts`)

Do you know a way to make the tock project work with docker-compose while not having to update the `hosts` file?

**Comment by francoisno** [comment]
Hi @adrienjoly,

From what I remember, we map hosts as a solution to the problem of Mongo member names, working both inside and outside Docker : 
- Mongo members being created as Docker containers, `setup.sh` configuring the _replica set_ using container names,
- When connecting to the _replica set_, those names are returned,
- Unfortunately, outside Docker container names can't work.

Note that mapping hosts is not required when running everything inside Docker, or to merely browse the database outside Docker (using Robot3T for instance and `localhost:27017`, not using the `replicaSet` connection mode). For programmatic use (Tock db clients), _replicaSet_ connection is mandatory because of Mongo _change streams_ feature.

Any expertise about Docker networking is welcome, hoping a simpler/less intrusive solution is possible :)

**Comment by adrienjoly** [comment]
> Note that mapping hosts is not required when running everything inside Docker

That's good to know! Thanks for your reply!

By any chance, could this issue be solved by using just one mongodb server, instead of the replica set? (for development purposes, at least)

**Comment by vsct-jburet** [comment]
as @francoisno said, replicaset conf is mandatory because tock uses change streams (see https://docs.mongodb.com/manual/changeStreams/ )

On linux, you can use your ip as host, because docker forwards ips on linux - we added the "mongo host hack" to be windows compliant.

If you change in https://github.com/theopenconversationkit/tock-docker/blob/master/docker-compose-mongo-only.yml the lines

```
      - MONGO1=mongo
      - MONGO2=mongo2
      - MONGO3=mongo3
```
by
```
      - MONGO1="yourip"
      - MONGO2="yourip"
      - MONGO3="yourip"
```

you can connect to this database from outside docker using `mongodb://localhost:27017,localhost:27018,localhost:27019/?replicaSet=tock` (which is the default conf in tock) 

So you have to do the same thing in the docker-compose file you use - but it works only with linux or mac - not with windows :)

HTH

**Comment by adrienjoly** [comment]
Thanks for sharing this very handy trick, Julien! 🙌

I'm not sure about when I'll find time to try this out but I'm confident that it should work, so I guess that we can close this ticket, if you want :-)

**Comment by francoisno** [comment]
Thanks for the feedback @adrienjoly 
I'll close the issue as soon as I add this trick to the documentation 😉
